import type { Metadata } from "next";
import { Playfair_Display, Sacramento } from "next/font/google";
import "./globals.css";

const headingFont = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
});
const contentFont = Sacramento({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-display',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${headingFont.variable} ${contentFont.variable}`}>{children}</body>
    </html>
  );
}
